import Pascal
import matplotlib.pyplot
f=Pascal.Pascal()
Y0=Pascal.Pascal.Y0(f)
Y1=Pascal.Pascal.Y1(f)
Y2=Pascal.Pascal.Y2(f)
Y3=Pascal.Pascal.Y3(f)
Y4=Pascal.Pascal.Y4(f)
F0=Pascal.Pascal.F0(f)
F1=Pascal.Pascal.F1(f)
F2=Pascal.Pascal.F2(f)
F3=Pascal.Pascal.F3(f)
F4=Pascal.Pascal.F4(f)
W0=Pascal.Pascal.W0(f)
W1=Pascal.Pascal.W1(f)
W2=Pascal.Pascal.W2(f)
W3=Pascal.Pascal.W3(f)
W4=Pascal.Pascal.W4(f)
SS6=Pascal.Pascal.SS6(f)
SS7=Pascal.Pascal.SS7(f)
Time=Pascal.Pascal.Time(f)
print(len(Y0))
print(len(Y1))
print(len(Y2))
print(len(Y3))
print(len(Y4))
print(len(Time))
fig=matplotlib.pyplot.figure()
p1=matplotlib.pyplot.plot(Time,Y0,label="Y0")
p2=matplotlib.pyplot.plot(Time,Y1, label="Y1")
p3=matplotlib.pyplot.plot(Time,Y2, label="Y2")
p4=matplotlib.pyplot.plot(Time,Y3, label="Y3")
p5=matplotlib.pyplot.plot(Time,Y4, label="Y4")
matplotlib.pyplot.ylabel("Y") # ось абсцисс
matplotlib.pyplot.xlabel("Time") # ось ординат
grid1 = matplotlib.pyplot.grid(True)
legend=matplotlib.pyplot.legend()
fig2=matplotlib.pyplot.figure()
f1=matplotlib.pyplot.plot(Time,F0, label="F0")
f2=matplotlib.pyplot.plot(Time,F1, label="F1")
f3=matplotlib.pyplot.plot(Time,F2, label="F2")
f4=matplotlib.pyplot.plot(Time,F3, label="F3")
f5=matplotlib.pyplot.plot(Time,F4, label="F4")
matplotlib.pyplot.ylabel("F") # ось абсцисс
matplotlib.pyplot.xlabel("Time") # ось ординат
grid2 = matplotlib.pyplot.grid(True)
legend2=matplotlib.pyplot.legend()
fig3=matplotlib.pyplot.figure()
w1=matplotlib.pyplot.plot(Time,W0, label="W0")
w2=matplotlib.pyplot.plot(Time,W1, label="W1")
w3=matplotlib.pyplot.plot(Time,W2, label="W2")
w4=matplotlib.pyplot.plot(Time,W3, label="W3")
w5=matplotlib.pyplot.plot(Time,W4, label="W4")
matplotlib.pyplot.ylabel("W") # ось абсцисс
matplotlib.pyplot.xlabel("Time") # ось ординат
grid3 = matplotlib.pyplot.grid(True)
legend3=matplotlib.pyplot.legend()
fig4=matplotlib.pyplot.figure()
w1=matplotlib.pyplot.plot(Time,SS6, label="SS6")
w2=matplotlib.pyplot.plot(Time,SS7, label="SS7")
matplotlib.pyplot.ylabel("SS") # ось абсцисс
matplotlib.pyplot.xlabel("Time") # ось ординат
matplotlib.pyplot.yscale('log')
grid4 = matplotlib.pyplot.grid(True)
legend4=matplotlib.pyplot.legend()
matplotlib.pyplot.show()
